### ISSUE TITLE
Question/Feature Request: React style event props

### ISSUE THREAD

**Issue by georeith** [michalochman/react-pixi-fiber#179]
### Description

The functions `pointerdown`, 'mousedown', etc should in my opinion be renamed to `onPointerDown` so that they match the [standard React event API](https://reactjs.org/docs/events.html). I understand that they follow the pixi naming convention but it makes applications written with `react-pixi-fiber` less compatible.

### Use case

My application is one of many possible rendering targets and the components of it are used by another application which expects to import my components and decorate them using the standard React mouse and pointer event API.

I'm aware I could proxy them through in each of my components, but it seems an odd decision to not follow the React style, what are your thoughts?

**Comment by michalochman** [comment]
Hi @georeith, there are multiple reasons:
1. This library was initially successor to [Izzimach/react-pixi](https://github.com/Izzimach/react-pixi) and still uses the same API so it's technically easy to migrate from React 15 to React 16+.
2. Not having to transform props makes this library lighter, which means it's easier to maintain and that it has less surface for bugs. It also makes barrier to entry lower because it's easy to just read Pixi documentation and use props in React code with the same names that you see in Pixi docs.
3. There is really no standard event API for React, the one you link is related strictly to ReactDOM 😉
4. This library does not implement [SyntheticEvent](https://reactjs.org/docs/events.html) API and events that are emitted by PixiJS do not conform to SyntheticEvent, they are instances of [InteractionEvent](https://pixijs.download/dev/docs/PIXI.interaction.InteractionEvent.html) which would be confusing.

I would suggest you to update the decorator functions to transform the prop names instead or create higher-order component to do this.

**Comment by georeith** [comment]
> I would suggest you to update the decorator functions to transform the prop names instead or create higher-order component to do this.

@michalochman are you referring to `customApplyProps` here?

**Comment by georeith** [comment]
Ah I've just found: https://github.com/Izzimach/react-pixi/blob/a25196251a13ed9bb116a8576d93e9fceac2a14c/src/ReactPIXI.js#L953

**Comment by michalochman** [comment]
Hi @georeith, it's described here as well:
https://github.com/michalochman/react-pixi-fiber#customapplypropsdisplayobject-oldprops-newprops-optional

It's not very visible in README, sorry about that. I will work on improving documentation after 1.0 release.

**Comment by georeith** [comment]
Great thanks for the help

**Comment by georeith** [comment]
One small suggestion is that `applyDisplayObjectProps` be exposed some other way than `this` as it then prevents you from using arrow functions.

**Comment by michalochman** [comment]
This limitation is intentional as this method is bound to the underlying `PIXI.DisplayObject` instance and only takes 2 arguments (old and new props).

If you want generic function to apply props then [`applyProps`](https://github.com/michalochman/react-pixi-fiber/blob/dce010c193b87dfce9eb14a939d4ae22be2f39ae/src/index.js#L19) (which takes instance, old and new props) is also exported:

```js
import { applyProps } from "react-pixi-fiber";
```

However this method is deprecated and will be replaced with `applyDisplayObjectProps` in version 1.0
